### ISSUE TITLE
cobertura-maven-plugin

### ISSUE THREAD

**Issue by muminc** [christ66/cobertura#10]
Hi,

Noticed cobertura-maven-plugin was updated to 2.6 last month. Do you look after this plugin? Is it is available anywhere on github for pull requests?

Thanks.

**Comment by christ66** [comment]
I am the maintainer of this plugin, but his plugin is not available for pull requests on github. If you would like a pull request, please use the codehaus interface to create a jira with with .diff file. The cobertura maven plugin actually uses subversion. See http://jira.codehaus.org/browse/MCOBERTURA and http://svn.codehaus.org/mojo/tags/cobertura-maven-plugin-2.6.

Thanks,
Steve.
