### ISSUE TITLE
Report Not Correct On Android

### ISSUE THREAD

**Issue by jamesguo** [christ66/cobertura#12]
@christ66 
I have used cobertura for my App.
After a few tests & get the report. I find some problems.

```
1，some line is actually executed，but in the report html it display not be executed.
2，FlightListFragment$1 coverage 78%
   FlightListFragment$2 coverage 56%
   But FlightListFragment self coverage 0% which was obviously wrong
```

**Comment by christ66** [comment]
@jamesguo Please log this issue to https://github.com/cobertura/cobertura as that is the main repository. Please also upgrade to the latest version of cobertura and verify you still encounter the same issues.
